# Generated by Django 3.1.2 on 2020-10-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201023_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='user',
            new_name='User',
        ),
    ]
