# Generated by Django 3.1.2 on 2020-10-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201023_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='User',
            new_name='user',
        ),
    ]
