# Generated by Django 3.1.2 on 2020-10-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='points',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
